### ISSUE TITLE
Python error in Index suggestion and Predicates used by this query widget

### ISSUE THREAD

**Issue by Marczeeee** [dalibo/powa-web#11]
I use Powa (3.0.0) with Powa-web and sometimes when I open a Query detail page the *Index suggestion* widget and the *Predicates used by this query* widget doesn't load and the "An error occured while loading this widget" text displayed instead. On the console the following Python error is shown:
```python
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
        callback()
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
        self._when_complete(method(*self.path_args, **self.path_kwargs),
      File "/home/user/powa-web-3.0.0/powa/dashboards.py", line 92, in get
        data = self.post_process(data, **url_params)
      File "/home/user/powa-web-3.0.0/powa/query.py", line 270, in post_process
        data["data"] = resolve_quals(conn, data["data"])
      File "/home/user/powa-web-3.0.0/powa/sql/__init__.py", line 226, in resolve_quals
        {"att_list": tuple(attname_to_look)}).scalar()
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 822, in scalar
        row = self.first()
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 806, in first
        self.cursor, self.context)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1027, in _handle_dbapi_exception
        util.reraise(*exc_info)
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 802, in first
        row = self._fetchone_impl()
      File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 698, in _fetchone_impl
        return self.cursor.fetchone()
      File "/home/user/powa-web-3.0.0/powa/compat.py", line 18, in <lambda>
        (JSON_OID,), "JSON", lambda data, cursor: json.loads(data))
      File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    TypeError: expected string or buffer
```

**Comment by rjuju** [comment]
It looks like there's a problem while retrieving the predicate informations.

Could you execute this query on the powa database when the problem occurs of show the result here? You need to change the **CHANGEME** for the actual queryid of the problematic query (available in the url, between **query** and **overview**) : 

```sql
SELECT qualid, powa_statements.queryid, query, powa_statements.dbid, to_json(quals) AS quals, sum(execution_count) AS execution_count, sum(occurences) AS occurences, sum(nbfiltered) / sum(occurences) AS avg_filter, CASE WHEN (sum(execution_count) = 0) THEN 0 ELSE (sum(nbfiltered) / CAST(sum(execution_count) AS NUMERIC)) * 100 END AS filter_ratio
FROM 
    (
    SELECT queryid, qualid, (unnested.records).*
    FROM (
        SELECT pqnh.qualid, pqnh.queryid, pqnh.dbid, pqnh.userid, pqnh.coalesce_range, unnest(records) as records
        FROM powa_qualstats_quals_history pqnh
        WHERE coalesce_range  && tstzrange(now() - interval '1 hour', now(), '[]')
    ) AS unnested
    WHERE tstzrange(now() - interval '1 hour', now(), '[]') @> (records).ts
    UNION ALL
    SELECT queryid, qualid, pqnc.ts, pqnc.occurences, pqnc.execution_count, pqnc.nbfiltered
    FROM powa_qualstats_quals_history_current pqnc
    WHERE tstzrange(now() - interval '1 hour', now(), '[]') @> pqnc.ts
    ) h
    JOIN powa_qualstats_quals pqnh USING (queryid, qualid)
     JOIN powa_statements ON powa_statements.queryid = pqnh.queryid 
WHERE powa_statements.queryid = CHANGEME GROUP BY qualid, powa_statements.queryid, powa_statements.dbid, powa_statements.query, quals
;
```

**Comment by Marczeeee** [comment]
The resultset of the query was empty for every problematic query.

**Comment by rjuju** [comment]
Ok.

Just to be sure, had the queries been run in the last hour when you check the results ?

Can you show some examples of involved query ?

**Comment by Marczeeee** [comment]
I usually use longer time intervals when checking the results, so it's possible that a query was run more than one hour before my check.
As soon as I can find a problematic query I'll show you.

**Comment by rjuju** [comment]
Hello,

Did this error raise again?

**Comment by Marczeeee** [comment]
No, so far it seems to be good.

**Comment by rjuju** [comment]
Ok. I'll close this issue for now, feel free to re-open it if the problem happens again.

**Comment by palabre** [comment]
Hi rjuju

I am having same issue with powa 3.1.1.  I

When I click on the Predicates TAB I have just following messages

An error occured while loading this widget 
No quals found for this query
And then no suggestion for any index

Can you help

regards

**Comment by rjuju** [comment]
I'll answer on https://github.com/dalibo/powa-web/issues/41 you opened at the same time
